name: Pull request notification 

on:
    [pull_request]
      
jobs:
    send_message:
        runs-on: ubuntu-latest
        steps:
        - name: New pull request
          if: (github.event.action == 'opened')
          uses: Ilshidur/action-discord@0.1.0
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          with:
            args: |
                New Legion TD pull request \"{{EVENT_PAYLOAD.pull_request.title}}\".
                {{EVENT_PAYLOAD.pull_request.html_url}}
                {{EVENT_PAYLOAD.pull_request.body}}
                
        - name: Pull request merged
          if: (github.event.action == 'closed') && github.event.pull_request.merged
          uses: Ilshidur/action-discord@0.1.0
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          with:
            args: |
                Merged pull request \"{{EVENT_PAYLOAD.pull_request.title}}\".
                {{EVENT_PAYLOAD.pull_request.html_url}}
