name: Pull request notification 

on:
    [pull_request]
      
jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - name: Discord notification
          if: github.event.action == 'synchronize'
          uses: Ilshidur/action-discord@0.1.0
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          with:
            args: |
                New Legion TD pull request \"{{EVENT_PAYLOAD.pull_request.title}}\".
                {{EVENT_PAYLOAD.pull_request.html_url}}
                {{EVENT_PAYLOAD.pull_request.body}}
                {{EVENT_PAYLOAD.action}}
                {{EVENT_PAYLOAD.merged}}
