name: Pull request notification 

on:
  [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      uses: Ilshidur/action-discord@0.0.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'New Legion TD pull request {{EVENT_PAYLOAD.pull_request.id}}.'
